# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_CGAL_Convex_hull_2', [dirname(__file__)])
        except ImportError:
            import _CGAL_Convex_hull_2
            return _CGAL_Convex_hull_2
        if fp is not None:
            try:
                _mod = imp.load_module('_CGAL_Convex_hull_2', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _CGAL_Convex_hull_2 = swig_import_helper()
    del swig_import_helper
else:
    import _CGAL_Convex_hull_2
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


import CGAL.CGAL_Kernel

def convex_hull_2(*args):
  return _CGAL_Convex_hull_2.convex_hull_2(*args)
convex_hull_2 = _CGAL_Convex_hull_2.convex_hull_2

def ch_bykat(*args):
  return _CGAL_Convex_hull_2.ch_bykat(*args)
ch_bykat = _CGAL_Convex_hull_2.ch_bykat

def ch_eddy(*args):
  return _CGAL_Convex_hull_2.ch_eddy(*args)
ch_eddy = _CGAL_Convex_hull_2.ch_eddy

def ch_graham_andrew(*args):
  return _CGAL_Convex_hull_2.ch_graham_andrew(*args)
ch_graham_andrew = _CGAL_Convex_hull_2.ch_graham_andrew

def ch_melkman(*args):
  return _CGAL_Convex_hull_2.ch_melkman(*args)
ch_melkman = _CGAL_Convex_hull_2.ch_melkman

def ch_jarvis(*args):
  return _CGAL_Convex_hull_2.ch_jarvis(*args)
ch_jarvis = _CGAL_Convex_hull_2.ch_jarvis

def lower_hull_points_2(*args):
  return _CGAL_Convex_hull_2.lower_hull_points_2(*args)
lower_hull_points_2 = _CGAL_Convex_hull_2.lower_hull_points_2

def upper_hull_points_2(*args):
  return _CGAL_Convex_hull_2.upper_hull_points_2(*args)
upper_hull_points_2 = _CGAL_Convex_hull_2.upper_hull_points_2

def ch_akl_toussaint(*args):
  return _CGAL_Convex_hull_2.ch_akl_toussaint(*args)
ch_akl_toussaint = _CGAL_Convex_hull_2.ch_akl_toussaint

def ch_graham_andrew_scan(*args):
  return _CGAL_Convex_hull_2.ch_graham_andrew_scan(*args)
ch_graham_andrew_scan = _CGAL_Convex_hull_2.ch_graham_andrew_scan

def ch_jarvis_march(*args):
  return _CGAL_Convex_hull_2.ch_jarvis_march(*args)
ch_jarvis_march = _CGAL_Convex_hull_2.ch_jarvis_march

def is_ccw_strongly_convex_2(*args):
  return _CGAL_Convex_hull_2.is_ccw_strongly_convex_2(*args)
is_ccw_strongly_convex_2 = _CGAL_Convex_hull_2.is_ccw_strongly_convex_2

def is_cw_strongly_convex_2(*args):
  return _CGAL_Convex_hull_2.is_cw_strongly_convex_2(*args)
is_cw_strongly_convex_2 = _CGAL_Convex_hull_2.is_cw_strongly_convex_2

def ch_n_point(*args):
  return _CGAL_Convex_hull_2.ch_n_point(*args)
ch_n_point = _CGAL_Convex_hull_2.ch_n_point

def ch_s_point(*args):
  return _CGAL_Convex_hull_2.ch_s_point(*args)
ch_s_point = _CGAL_Convex_hull_2.ch_s_point

def ch_e_point(*args):
  return _CGAL_Convex_hull_2.ch_e_point(*args)
ch_e_point = _CGAL_Convex_hull_2.ch_e_point

def ch_w_point(*args):
  return _CGAL_Convex_hull_2.ch_w_point(*args)
ch_w_point = _CGAL_Convex_hull_2.ch_w_point

def ch_we_point(*args):
  return _CGAL_Convex_hull_2.ch_we_point(*args)
ch_we_point = _CGAL_Convex_hull_2.ch_we_point

def ch_ns_point(*args):
  return _CGAL_Convex_hull_2.ch_ns_point(*args)
ch_ns_point = _CGAL_Convex_hull_2.ch_ns_point

def ch_nswe_point(*args):
  return _CGAL_Convex_hull_2.ch_nswe_point(*args)
ch_nswe_point = _CGAL_Convex_hull_2.ch_nswe_point
# This file is compatible with both classic and new-style classes.


